output: coherences_transposed

imports:
  preproc:
    - Coherences
    - Windower

preproc:
  - Windower:
      window: 20
  - Coherences:
      window: 512
      overlap: 0.5
      fs: 400
      frequencies: [[0.1, 4], [4, 8], [8, 15], [15, 30], [30, 90], [90, 170]]
      aggregate: False
      transpose: True
