output: relative_log_power

imports:
  preproc:
    - RelativeLogPower
    - Windower

preproc:
  - Windower:
      window: 20
  - RelativeLogPower:
      window: 512
      overlap: 0.25
      fs: 400
      frequencies: [[0.1, 4], [4, 8], [8, 15], [15, 30], [30, 90], [90, 170]]
