output: power_ratios

imports:
  preproc:
    - PowerRatios
    - Windower

preproc:
  - Windower:
      window: 20
  - PowerRatios:
      window: 512
      overlap: 0.25
      fs: 200
      frequencies: [[0.1, 4], [4, 8], [8, 15], [15, 30], [30, 50]]
